version: "3.5"

services:
  sisaf:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sisaf
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    ports:
      - "5000:5432"

volumes:
  data:
